import { Item, ItemType, Quest, Rarity } from './types';

// Helper to create simple IDs
const id = (name: string) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

export const ITEMS: Item[] = [
  {
    id: id('Advanced ARC Powercell'),
    name: 'Advanced ARC Powercell',
    description: 'A high-capacity energy storage unit used in advanced ARC machinery.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 1,
    recycleYield: [{ itemId: id('ARC Powercell'), amount: 2 }],
    requiredForWorkshop: false,
  },
  {
    id: id('Advanced Electrical Components'),
    name: 'Advanced Electrical Components',
    description: 'Sophisticated circuitry for high-tech applications.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1750,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Electrical Components'), amount: 1 },
      { itemId: id('Wires'), amount: 1 },
    ],
    requiredForWorkshop: true,
    requiredForExpedition: true,
  },
  {
    id: id('Advanced Mechanical Components'),
    name: 'Advanced Mechanical Components',
    description: 'Precision-engineered parts for complex machinery.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1750,
    weight: 0.8,
    recycleYield: [
      { itemId: id('Mechanical Components'), amount: 1 },
      { itemId: id('Wires'), amount: 1 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Agave'),
    name: 'Agave',
    description: 'A hardy succulent plant.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.2,
    recycleYield: [{ itemId: id('Assorted Seeds'), amount: 3 }],
  },
  {
    id: id('Air Freshener'),
    name: 'Air Freshener',
    description: 'Still holds a faint scent of pine.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.VALUABLE,
    sellPrice: 2000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Alarm Clock'),
    name: 'Alarm Clock',
    description: 'A relic of a time when people had schedules.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Processor'), amount: 1 },
      { itemId: id('Plastic Parts'), amount: 6 },
    ],
  },
  {
    id: id('Antiseptic'),
    name: 'Antiseptic',
    description: 'Medical grade cleaning solution.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.2,
    recycleYield: [{ itemId: id('Chemicals'), amount: 10 }],
    requiredForWorkshop: true,
  },
  {
    id: id('Apricot'),
    name: 'Apricot',
    description: 'Fresh fruit, a rare treat.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.1,
    recycleYield: [{ itemId: id('Assorted Seeds'), amount: 3 }],
  },
  {
    id: id('ARC Alloy'),
    name: 'ARC Alloy',
    description: 'Lightweight and incredibly durable metal alloy harvested from ARC units.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 200,
    weight: 0.5,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 2 }],
    requiredForWorkshop: true,
    requiredForExpedition: true,
  },
  {
    id: id('ARC Circuitry'),
    name: 'ARC Circuitry',
    description: 'The nervous system of ARC machines.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.3,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 2 }],
    requiredForWorkshop: true,
  },
  {
    id: id('ARC Coolant'),
    name: 'ARC Coolant',
    description: 'Prevents ARC units from overheating.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [{ itemId: id('Chemicals'), amount: 16 }],
  },
  {
    id: id('ARC Flex Rubber'),
    name: 'ARC Flex Rubber',
    description: 'Synthetic rubber with high elasticity.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.4,
    recycleYield: [{ itemId: id('Rubber Parts'), amount: 16 }],
  },
  {
    id: id('ARC Motion Core'),
    name: 'ARC Motion Core',
    description: 'The kinetic heart of an ARC unit.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 2 }],
    requiredForWorkshop: true,
  },
  {
    id: id('ARC Performance Steel'),
    name: 'ARC Performance Steel',
    description: 'High-grade steel used in heavy ARC units.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 12 }],
  },
  {
    id: id('ARC Powercell'),
    name: 'ARC Powercell',
    description: 'Standard energy unit for ARC drones.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.5,
    recycleYield: [],
    requiredForWorkshop: true,
  },
  {
    id: id('ARC Synthetic Resin'),
    name: 'ARC Synthetic Resin',
    description: 'Moldable material used in ARC construction.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.3,
    recycleYield: [{ itemId: id('Plastic Parts'), amount: 14 }],
  },
  {
    id: id('ARC Thermo Lining'),
    name: 'ARC Thermo Lining',
    description: 'Insulation material from ARC units.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.2,
    recycleYield: [{ itemId: id('Fabric'), amount: 16 }],
  },
  {
    id: id('Assorted Seeds'),
    name: 'Assorted Seeds',
    description: 'A mix of viable seeds.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 100,
    weight: 0.05,
    recycleYield: [],
  },
  {
    id: id('Bastion Cell'),
    name: 'Bastion Cell',
    description: 'Power core from a Bastion unit.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 5000,
    weight: 2.0,
    recycleYield: [
      { itemId: id('ARC Motion Core'), amount: 2 },
      { itemId: id('Advanced Mechanical Components'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Battery'),
    name: 'Battery',
    description: 'Standard chemical battery.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 250,
    weight: 0.3,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 2 }],
    requiredForExpedition: true,
  },
  {
    id: id('Bicycle Pump'),
    name: 'Bicycle Pump',
    description: 'Manual air pump.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Canister'), amount: 4 },
      { itemId: id('Metal Parts'), amount: 10 },
    ],
  },
  {
    id: id('Bloated Tuna Can'),
    name: 'Bloated Tuna Can',
    description: 'Probably not safe to eat.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 1000,
    weight: 0.2,
    recycleYield: [],
  },
  {
    id: id('Blue Gate Communication Tower Key'),
    name: 'Blue Gate Communication Tower Key',
    description: 'Access key for the tower.',
    rarity: Rarity.RARE,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Blue Gate Confiscation Room Key'),
    name: 'Blue Gate Confiscation Room Key',
    description: 'Key to the confiscation room.',
    rarity: Rarity.EPIC,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Blue Gate Cellar Key'),
    name: 'Blue Gate Cellar Key',
    description: 'Key to a cellar in Blue Gate.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Blue Gate Village Key'),
    name: 'Blue Gate Village Key',
    description: 'Key to a village structure.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Bombardier Cell'),
    name: 'Bombardier Cell',
    description: 'Power cell from a Bombardier.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 5000,
    weight: 2.0,
    recycleYield: [
      { itemId: id('Advanced Mechanical Components'), amount: 2 },
      { itemId: id('ARC Alloy'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Breathtaking Snow Globe'),
    name: 'Breathtaking Snow Globe',
    description: 'A pristine pre-collapse souvenir.',
    rarity: Rarity.EPIC,
    type: ItemType.VALUABLE,
    sellPrice: 7000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Broken Flashlight'),
    name: 'Broken Flashlight',
    description: 'No longer lights up.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.3,
    recycleYield: [
      { itemId: id('Battery'), amount: 3 },
      { itemId: id('Metal Parts'), amount: 7 },
    ],
  },
  {
    id: id('Broken Guidance System'),
    name: 'Broken Guidance System',
    description: 'Smashed navigation computer.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 1.0,
    recycleYield: [{ itemId: id('Processor'), amount: 4 }],
  },
  {
    id: id('Broken Handheld Radio'),
    name: 'Broken Handheld Radio',
    description: 'Static is all you hear.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Sensors'), amount: 3 },
      { itemId: id('Wires'), amount: 3 },
    ],
  },
  {
    id: id('Broken Taser'),
    name: 'Broken Taser',
    description: 'Discharged and broken.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Battery'), amount: 2 },
      { itemId: id('Wires'), amount: 2 },
    ],
  },
  {
    id: id('Buried City Hospital Key'),
    name: 'Buried City Hospital Key',
    description: 'Access to the hospital.',
    rarity: Rarity.RARE,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Buried City JKV Employee Access Card'),
    name: 'Buried City JKV Employee Access Card',
    description: 'Access card for JKV employees.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Buried City Residential Mastery Key'),
    name: 'Buried City Residential Mastery Key',
    description: 'Master key for residential areas.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Buried City Town Hall Key'),
    name: 'Buried City Town Hall Key',
    description: 'Key to the Town Hall.',
    rarity: Rarity.EPIC,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Burned ARC Circuitry'),
    name: 'Burned ARC Circuitry',
    description: 'Fried circuits.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.2,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 2 }],
  },
  {
    id: id('Camera Lens'),
    name: 'Camera Lens',
    description: 'A glass lens.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.2,
    recycleYield: [{ itemId: id('Plastic Parts'), amount: 8 }],
  },
  {
    id: id('Candle Holder'),
    name: 'Candle Holder',
    description: 'Decorative metal holder.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.5,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 8 }],
  },
  {
    id: id('Canister'),
    name: 'Canister',
    description: 'Empty container.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 300,
    weight: 0.3,
    recycleYield: [{ itemId: id('Plastic Parts'), amount: 3 }],
  },
  {
    id: id('Cat Bed'),
    name: 'Cat Bed',
    description: 'Soft place for a pet.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [],
  },
  {
    id: id('Chemicals'),
    name: 'Chemicals',
    description: 'Basic chemical compounds.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 50,
    weight: 0.2,
    recycleYield: [],
    requiredForWorkshop: true,
  },
  {
    id: id('Coffee Pot'),
    name: 'Coffee Pot',
    description: 'Glass pot for brewing coffee.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Complex Gun Parts'),
    name: 'Complex Gun Parts',
    description: 'Advanced weapon components.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [{ itemId: id('Simple Gun Parts'), amount: 3 }],
  },
  {
    id: id('Coolant'),
    name: 'Coolant',
    description: 'Liquid for heat regulation.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Chemicals'), amount: 5 },
      { itemId: id('Oil'), amount: 2 },
    ],
  },
  {
    id: id('Cooling Coil'),
    name: 'Cooling Coil',
    description: 'Metal coil for cooling systems.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.4,
    recycleYield: [
      { itemId: id('Chemicals'), amount: 6 },
      { itemId: id('Steel Spring'), amount: 2 },
    ],
  },
  {
    id: id('Cooling Fan'),
    name: 'Cooling Fan',
    description: 'Electric fan.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Plastic Parts'), amount: 14 },
      { itemId: id('Battery'), amount: 4 },
    ],
    requiredForExpedition: true,
  },
  {
    id: id('Cracked Bioscanner'),
    name: 'Cracked Bioscanner',
    description: 'Damaged scanner.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Rubber Parts'), amount: 3 },
      { itemId: id('Battery'), amount: 5 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Crude Explosives'),
    name: 'Crude Explosives',
    description: 'Unstable explosive material.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.5,
    recycleYield: [{ itemId: id('Chemicals'), amount: 3 }],
    requiredForWorkshop: true,
  },
  {
    id: id('Crumpled Plastic Bottle'),
    name: 'Crumpled Plastic Bottle',
    description: 'Garbage to some, resources to others.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 80,
    weight: 0.1,
    recycleYield: [{ itemId: id('Plastic Parts'), amount: 3 }],
  },
  {
    id: id('Dam Control Tower Key'),
    name: 'Dam Control Tower Key',
    description: 'Access to the Dam Control Tower.',
    rarity: Rarity.EPIC,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Dam Staff Room Key'),
    name: 'Dam Staff Room Key',
    description: 'Key to the staff room.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Dam Surveillance Key'),
    name: 'Dam Surveillance Key',
    description: 'Key to the surveillance room.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Dam Testing Annex Key'),
    name: 'Dam Testing Annex Key',
    description: 'Key to the testing annex.',
    rarity: Rarity.RARE,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Dam Utility Key'),
    name: 'Dam Utility Key',
    description: 'Key to utility areas.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Damaged ARC Motion Core'),
    name: 'Damaged ARC Motion Core',
    description: 'Malfunctioning core.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 1.0,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 2 }],
  },
  {
    id: id('Damaged ARC Powercell'),
    name: 'Damaged ARC Powercell',
    description: 'Leaking energy cell.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 293,
    weight: 0.5,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 1 }],
  },
  {
    id: id('Damaged Fireball Burner'),
    name: 'Damaged Fireball Burner',
    description: 'Broken flamethrower part.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.5,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 1 }],
  },
  {
    id: id('Damaged Heat Sink'),
    name: 'Damaged Heat Sink',
    description: 'Ineffective cooling part.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Metal Parts'), amount: 6 },
      { itemId: id('Wires'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Damaged Hornet Driver'),
    name: 'Damaged Hornet Driver',
    description: 'Busted propulsion system.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.5,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 2 }],
  },
  {
    id: id('Damaged Rocketeer Driver'),
    name: 'Damaged Rocketeer Driver',
    description: 'Broken rocket system.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 1.0,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 3 }],
  },
  {
    id: id('Damaged Snitch Scanner'),
    name: 'Damaged Snitch Scanner',
    description: 'Broken sensor array.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 659,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Damaged Tick Pod'),
    name: 'Damaged Tick Pod',
    description: 'Empty pod casing.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.5,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 1 }],
  },
  {
    id: id('Damaged Wasp Driver'),
    name: 'Damaged Wasp Driver',
    description: 'Crushed flight component.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.5,
    recycleYield: [{ itemId: id('ARC Alloy'), amount: 1 }],
  },
  {
    id: id('Dart Board'),
    name: 'Dart Board',
    description: 'Game equipment.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.VALUABLE,
    sellPrice: 2000,
    weight: 1.0,
    recycleYield: [],
  },
  {
    id: id('Deflated Football'),
    name: 'Deflated Football',
    description: 'Sad sports equipment.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.4,
    recycleYield: [{ itemId: id('Rubber Parts'), amount: 15 }],
  },
  {
    id: id('Degraded ARC Rubber'),
    name: 'Degraded ARC Rubber',
    description: 'Brittle rubber.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.3,
    recycleYield: [{ itemId: id('Rubber Parts'), amount: 11 }],
  },
  {
    id: id('Diving Goggles'),
    name: 'Diving Goggles',
    description: 'For underwater vision.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.2,
    recycleYield: [{ itemId: id('Rubber Parts'), amount: 12 }],
  },
  {
    id: id('Dog Collar'),
    name: 'Dog Collar',
    description: 'Pet accessory.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.1,
    recycleYield: [
      { itemId: id('Fabric'), amount: 8 },
      { itemId: id('Metal Parts'), amount: 1 },
    ],
  },
  {
    id: id('Dried-Out ARC Resin'),
    name: 'Dried-Out ARC Resin',
    description: 'Hardened resin.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.2,
    recycleYield: [{ itemId: id('Plastic Parts'), amount: 9 }],
  },
  {
    id: id('Duct Tape'),
    name: 'Duct Tape',
    description: 'Fixes everything.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 300,
    weight: 0.2,
    recycleYield: [{ itemId: id('Fabric'), amount: 3 }],
  },
  {
    id: id('Durable Cloth'),
    name: 'Durable Cloth',
    description: 'Heavy-duty fabric.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.3,
    recycleYield: [{ itemId: id('Fabric'), amount: 6 }],
    requiredForWorkshop: true,
    requiredForExpedition: true,
  },
  {
    id: id('Electrical Components'),
    name: 'Electrical Components',
    description: 'Standard electronics.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.3,
    recycleYield: [
      { itemId: id('Plastic Parts'), amount: 3 },
      { itemId: id('Rubber Parts'), amount: 3 },
    ],
    requiredForWorkshop: true,
    requiredForExpedition: true,
  },
  {
    id: id('Empty Wine Bottle'),
    name: 'Empty Wine Bottle',
    description: 'Just glass.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Exodus Modules'),
    name: 'Exodus Modules',
    description: 'High-tech component.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 2750,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Magnet'), amount: 2 },
      { itemId: id('Mechanical Components'), amount: 1 },
    ],
    requiredForExpedition: true,
  },
  {
    id: id('Expired Pasta'),
    name: 'Expired Pasta',
    description: 'Do not eat.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 1000,
    weight: 0.2,
    recycleYield: [],
  },
  {
    id: id('Expired Respirator'),
    name: 'Expired Respirator',
    description: 'Old breathing mask.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.3,
    recycleYield: [
      { itemId: id('Rubber Parts'), amount: 8 },
      { itemId: id('Fabric'), amount: 4 },
    ],
  },
  {
    id: id('Explosive Compound'),
    name: 'Explosive Compound',
    description: 'Dangerous material.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [{ itemId: id('Crude Explosives'), amount: 2 }],
    requiredForWorkshop: true,
  },
  {
    id: id('Fabric'),
    name: 'Fabric',
    description: 'Cloth scraps.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 50,
    weight: 0.1,
    recycleYield: [],
    requiredForWorkshop: true,
  },
  {
    id: id('Faded Photograph'),
    name: 'Faded Photograph',
    description: 'A memory of someone.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 640,
    weight: 0.01,
    recycleYield: [],
  },
  {
    id: id('Fertilizer'),
    name: 'Fertilizer',
    description: 'Growth enhancer.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [{ itemId: id('Assorted Seeds'), amount: 2 }],
  },
  {
    id: id('Film Reel'),
    name: 'Film Reel',
    description: 'Old movie reel.',
    rarity: Rarity.RARE,
    type: ItemType.VALUABLE,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Fine Wristwatch'),
    name: 'Fine Wristwatch',
    description: 'Luxury item from before.',
    rarity: Rarity.RARE,
    type: ItemType.VALUABLE,
    sellPrice: 3000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Fireball Burner'),
    name: 'Fireball Burner',
    description: 'Part of a Fireball unit.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.8,
    recycleYield: [
      { itemId: id('ARC Alloy'), amount: 1 },
      { itemId: id('Chemicals'), amount: 1 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Frequency Modulation Box'),
    name: 'Frequency Modulation Box',
    description: 'Sound equipment.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Advanced Electrical Components'), amount: 1 },
      { itemId: id('Speaker Component'), amount: 1 },
    ],
  },
  {
    id: id('Fried Motherboard'),
    name: 'Fried Motherboard',
    description: 'Short-circuited board.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Plastic Parts'), amount: 5 },
      { itemId: id('Electrical Components'), amount: 1 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Frying Pan'),
    name: 'Frying Pan',
    description: 'Cast iron.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 1.5,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 8 }],
  },
  {
    id: id('Garlic Press'),
    name: 'Garlic Press',
    description: 'Kitchen tool.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.2,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 12 }],
  },
  {
    id: id('Geiger Counter'),
    name: 'Geiger Counter',
    description: 'Measures radiation.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 3500,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Battery'), amount: 3 },
      { itemId: id('Exodus Modules'), amount: 1 },
    ],
  },
  {
    id: id('Great Mullein'),
    name: 'Great Mullein',
    description: 'Medicinal plant.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 300,
    weight: 0.2,
    recycleYield: [{ itemId: id('Assorted Seeds'), amount: 4 }],
  },
  {
    id: id('Headphones'),
    name: 'Headphones',
    description: 'Audio device.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.3,
    recycleYield: [
      { itemId: id('Rubber Parts'), amount: 6 },
      { itemId: id('Speaker Component'), amount: 2 },
    ],
  },
  {
    id: id('Heavy Gun Parts'),
    name: 'Heavy Gun Parts',
    description: 'Components for heavy weapons.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 700,
    weight: 1.0,
    recycleYield: [{ itemId: id('Simple Gun Parts'), amount: 2 }],
  },
  {
    id: id('Hornet Driver'),
    name: 'Hornet Driver',
    description: 'Engine from a Hornet.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('ARC Alloy'), amount: 2 },
      { itemId: id('Electrical Components'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Household Cleaner'),
    name: 'Household Cleaner',
    description: 'Bleach mostly.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.5,
    recycleYield: [{ itemId: id('Chemicals'), amount: 13 }],
  },
  {
    id: id('Humidifier'),
    name: 'Humidifier',
    description: 'Adds moisture to air.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Canister'), amount: 2 },
      { itemId: id('Wires'), amount: 2 },
    ],
    requiredForExpedition: true,
  },
  {
    id: id('Ice Cream Scooper'),
    name: 'Ice Cream Scooper',
    description: 'For serving frozen treats.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.2,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 7 }],
  },
  {
    id: id('Impure ARC Coolant'),
    name: 'Impure ARC Coolant',
    description: 'Contaminated coolant.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.5,
    recycleYield: [{ itemId: id('Chemicals'), amount: 13 }],
  },
  {
    id: id('Industrial Battery'),
    name: 'Industrial Battery',
    description: 'Heavy duty power.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 2.0,
    recycleYield: [
      { itemId: id('Chemicals'), amount: 7 },
      { itemId: id('Battery'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Industrial Charger'),
    name: 'Industrial Charger',
    description: 'High voltage charger.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Metal Parts'), amount: 5 },
      { itemId: id('Voltage Converter'), amount: 1 },
    ],
  },
  {
    id: id('Industrial Magnet'),
    name: 'Industrial Magnet',
    description: 'Strong magnet.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Magnet'), amount: 2 },
      { itemId: id('Metal Parts'), amount: 4 },
    ],
  },
  {
    id: id('Ion Sputter'),
    name: 'Ion Sputter',
    description: 'High-tech device.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 6000,
    weight: 1.5,
    recycleYield: [
      { itemId: id('Voltage Converter'), amount: 4 },
      { itemId: id('Exodus Modules'), amount: 1 },
    ],
  },
  {
    id: id('Laboratory Reagents'),
    name: 'Laboratory Reagents',
    description: 'Science chemicals.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Chemicals'), amount: 2 },
      { itemId: id('Crude Explosives'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id("Lance's Mixtape (5th Edition)"),
    name: "Lance's Mixtape (5th Edition)",
    description: 'Fire tracks.',
    rarity: Rarity.EPIC,
    type: ItemType.VALUABLE,
    sellPrice: 10000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Lemon'),
    name: 'Lemon',
    description: 'Sour fruit.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.1,
    recycleYield: [{ itemId: id('Assorted Seeds'), amount: 3 }],
  },
  {
    id: id('Leaper Pulse Unit'),
    name: 'Leaper Pulse Unit',
    description: 'Component from a Leaper.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 5000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Advanced Mechanical Components'), amount: 2 },
      { itemId: id('ARC Alloy'), amount: 3 },
    ],
    requiredForWorkshop: true,
    requiredForExpedition: true,
  },
  {
    id: id('Light Bulb'),
    name: 'Light Bulb',
    description: 'Fragile glass bulb.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.VALUABLE,
    sellPrice: 2000,
    weight: 0.1,
    recycleYield: [],
    requiredForExpedition: true,
  },
  {
    id: id('Light Gun Parts'),
    name: 'Light Gun Parts',
    description: 'Parts for small arms.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 700,
    weight: 0.5,
    recycleYield: [{ itemId: id('Simple Gun Parts'), amount: 2 }],
  },
  {
    id: id('Magnet'),
    name: 'Magnet',
    description: 'Standard magnet.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 300,
    weight: 0.5,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 3 }],
  },
  {
    id: id('Magnetic Accelerator'),
    name: 'Magnetic Accelerator',
    description: 'Weapon component.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 5500,
    weight: 1.5,
    recycleYield: [
      { itemId: id('Advanced Mechanical Components'), amount: 1 },
      { itemId: id('ARC Motion Core'), amount: 1 },
    ],
    requiredForExpedition: true,
  },
  {
    id: id('Magnetron'),
    name: 'Magnetron',
    description: 'Microwave component.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 6000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Magnetic Accelerator'), amount: 1 },
      { itemId: id('Steel Spring'), amount: 1 },
    ],
  },
  {
    id: id('Matriarch Reactor'),
    name: 'Matriarch Reactor',
    description: 'Boss component.',
    rarity: Rarity.LEGENDARY,
    type: ItemType.MATERIAL,
    sellPrice: 13000,
    weight: 5.0,
    recycleYield: [
      { itemId: id('Power Rod'), amount: 1 },
      { itemId: id('Magnetic Accelerator'), amount: 1 },
    ],
  },
  {
    id: id('Mechanical Components'),
    name: 'Mechanical Components',
    description: 'Moving parts.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Metal Parts'), amount: 3 },
      { itemId: id('Rubber Parts'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Medium Gun Parts'),
    name: 'Medium Gun Parts',
    description: 'Parts for rifles.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 700,
    weight: 0.8,
    recycleYield: [{ itemId: id('Simple Gun Parts'), amount: 2 }],
  },
  {
    id: id('Metal Brackets'),
    name: 'Metal Brackets',
    description: 'Support pieces.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.5,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 8 }],
  },
  {
    id: id('Metal Parts'),
    name: 'Metal Parts',
    description: 'Scrap metal.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 75,
    weight: 0.1,
    recycleYield: [],
    requiredForWorkshop: true,
    requiredForExpedition: true,
  },
  {
    id: id('Microscope'),
    name: 'Microscope',
    description: 'Scientific instrument.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Advanced Mechanical Components'), amount: 1 },
      { itemId: id('Magnet'), amount: 3 },
    ],
  },
  {
    id: id('Mini Centrifuge'),
    name: 'Mini Centrifuge',
    description: 'Lab equipment.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Advanced Mechanical Components'), amount: 1 },
      { itemId: id('Canister'), amount: 2 },
    ],
  },
  {
    id: id('Mod Components'),
    name: 'Mod Components',
    description: 'Weapon modification parts.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Mechanical Components'), amount: 1 },
      { itemId: id('Steel Spring'), amount: 1 },
    ],
  },
  {
    id: id('Moss'),
    name: 'Moss',
    description: 'Plant matter.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 500,
    weight: 0.1,
    recycleYield: [{ itemId: id('Assorted Seeds'), amount: 3 }],
  },
  {
    id: id('Motor'),
    name: 'Motor',
    description: 'Electric motor.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.5,
    recycleYield: [
      { itemId: id('Oil'), amount: 2 },
      { itemId: id('Mechanical Components'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Mushroom'),
    name: 'Mushroom',
    description: 'Fungus.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Music Album'),
    name: 'Music Album',
    description: 'Vinyl record.',
    rarity: Rarity.RARE,
    type: ItemType.VALUABLE,
    sellPrice: 3000,
    weight: 0.2,
    recycleYield: [],
  },
  {
    id: id('Music Box'),
    name: 'Music Box',
    description: 'Plays a tune.',
    rarity: Rarity.RARE,
    type: ItemType.VALUABLE,
    sellPrice: 5000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Number Plate'),
    name: 'Number Plate',
    description: 'Vehicle identifier.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 80,
    weight: 0.2,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 3 }],
  },
  {
    id: id('Oil'),
    name: 'Oil',
    description: 'Lubricant.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 300,
    weight: 0.5,
    recycleYield: [{ itemId: id('Chemicals'), amount: 3 }],
  },
  {
    id: id('Olives'),
    name: 'Olives',
    description: 'Jar of olives.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.2,
    recycleYield: [{ itemId: id('Assorted Seeds'), amount: 2 }],
  },
  {
    id: id('Painted Box'),
    name: 'Painted Box',
    description: 'Decorative box.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Patrol Car Key'),
    name: 'Patrol Car Key',
    description: 'Key to a police car.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Plastic Parts'),
    name: 'Plastic Parts',
    description: 'Scrap plastic.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 60,
    weight: 0.1,
    recycleYield: [],
    requiredForWorkshop: true,
  },
  {
    id: id('Playing Cards'),
    name: 'Playing Cards',
    description: 'Deck of cards.',
    rarity: Rarity.RARE,
    type: ItemType.VALUABLE,
    sellPrice: 5000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Polluted Air Filter'),
    name: 'Polluted Air Filter',
    description: 'Dirty filter.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Fabric'), amount: 6 },
      { itemId: id('Oil'), amount: 2 },
    ],
  },
  {
    id: id('Pop Trigger'),
    name: 'Pop Trigger',
    description: 'Explosive mechanism.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Crude Explosives'), amount: 1 },
      { itemId: id('ARC Alloy'), amount: 1 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Portable TV'),
    name: 'Portable TV',
    description: 'Small television.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 2.0,
    recycleYield: [
      { itemId: id('Battery'), amount: 2 },
      { itemId: id('Wires'), amount: 6 },
    ],
  },
  {
    id: id('Poster of Natural Wonders'),
    name: 'Poster of Natural Wonders',
    description: 'Wall art.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.VALUABLE,
    sellPrice: 2000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Pottery'),
    name: 'Pottery',
    description: 'Clay pot.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.VALUABLE,
    sellPrice: 2000,
    weight: 1.0,
    recycleYield: [],
  },
  {
    id: id('Power Bank'),
    name: 'Power Bank',
    description: 'Portable charger.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Battery'), amount: 2 },
      { itemId: id('Wires'), amount: 2 },
    ],
  },
  {
    id: id('Power Cable'),
    name: 'Power Cable',
    description: 'Heavy duty cable.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [{ itemId: id('Wires'), amount: 4 }],
    requiredForWorkshop: true,
  },
  {
    id: id('Power Rod'),
    name: 'Power Rod',
    description: 'Energy conduit.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 5500,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Advanced Electrical Components'), amount: 1 },
      { itemId: id('ARC Circuitry'), amount: 1 },
    ],
  },
  {
    id: id('Prickly Pear'),
    name: 'Prickly Pear',
    description: 'Cactus fruit.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.1,
    recycleYield: [{ itemId: id('Assorted Seeds'), amount: 3 }],
  },
  {
    id: id('Processor'),
    name: 'Processor',
    description: 'Computing chip.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 500,
    weight: 0.05,
    recycleYield: [
      { itemId: id('Wires'), amount: 1 },
      { itemId: id('Plastic Parts'), amount: 1 },
    ],
  },
  {
    id: id('Projector'),
    name: 'Projector',
    description: 'Displays images.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 1.5,
    recycleYield: [
      { itemId: id('Processor'), amount: 1 },
      { itemId: id('Wires'), amount: 2 },
    ],
  },
  {
    id: id('Queen Reactor'),
    name: 'Queen Reactor',
    description: 'Core of a Queen unit.',
    rarity: Rarity.LEGENDARY,
    type: ItemType.MATERIAL,
    sellPrice: 13000,
    weight: 5.0,
    recycleYield: [
      { itemId: id('Power Rod'), amount: 1 },
      { itemId: id('Magnetic Accelerator'), amount: 1 },
    ],
  },
  {
    id: id('Radio'),
    name: 'Radio',
    description: 'Receives signals.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Speaker Component'), amount: 1 },
      { itemId: id('Sensors'), amount: 1 },
    ],
  },
  {
    id: id('Radio Relay'),
    name: 'Radio Relay',
    description: 'Boosts signals.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 1.5,
    recycleYield: [
      { itemId: id('Speaker Component'), amount: 2 },
      { itemId: id('Sensors'), amount: 2 },
    ],
  },
  {
    id: id('Raider Hatch Key'),
    name: 'Raider Hatch Key',
    description: 'Key to a raider stash.',
    rarity: Rarity.RARE,
    type: ItemType.KEY_ITEM,
    sellPrice: 1000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Red Coral Jewelry'),
    name: 'Red Coral Jewelry',
    description: 'Pretty necklace.',
    rarity: Rarity.RARE,
    type: ItemType.VALUABLE,
    sellPrice: 5000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Remote Control'),
    name: 'Remote Control',
    description: 'For a TV.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.2,
    recycleYield: [
      { itemId: id('Plastic Parts'), amount: 2 },
      { itemId: id('Sensors'), amount: 1 },
    ],
  },
  {
    id: id('Resin'),
    name: 'Resin',
    description: 'Sticky substance.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.2,
    recycleYield: [],
  },
  {
    id: id('Ripped Safety Vest'),
    name: 'Ripped Safety Vest',
    description: 'High vis.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Magnet'), amount: 1 },
      { itemId: id('Durable Cloth'), amount: 1 },
    ],
  },
  {
    id: id('Rocket Thruster'),
    name: 'Rocket Thruster',
    description: 'Rocket engine part.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 2.0,
    recycleYield: [
      { itemId: id('Synthesized Fuel'), amount: 2 },
      { itemId: id('Metal Parts'), amount: 6 },
    ],
  },
  {
    id: id('Rocketeer Driver'),
    name: 'Rocketeer Driver',
    description: 'Propulsion system.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 5000,
    weight: 2.0,
    recycleYield: [
      { itemId: id('Advanced Electrical Components'), amount: 2 },
      { itemId: id('ARC Alloy'), amount: 3 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Roots'),
    name: 'Roots',
    description: 'Edible?',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.2,
    recycleYield: [{ itemId: id('Assorted Seeds'), amount: 1 }],
  },
  {
    id: id('Rope'),
    name: 'Rope',
    description: 'Cordage.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 500,
    weight: 0.5,
    recycleYield: [{ itemId: id('Fabric'), amount: 5 }],
  },
  {
    id: id('Rosary'),
    name: 'Rosary',
    description: 'Religious beads.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 2000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Rotary Encoder'),
    name: 'Rotary Encoder',
    description: 'Precision sensor.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Electrical Components'), amount: 2 },
      { itemId: id('Processor'), amount: 2 },
    ],
  },
  {
    id: id('Rubber Duck'),
    name: 'Rubber Duck',
    description: 'Bath toy.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 1000,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Rubber Pad'),
    name: 'Rubber Pad',
    description: 'Shock absorber.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [{ itemId: id('Rubber Parts'), amount: 18 }],
  },
  {
    id: id('Rubber Parts'),
    name: 'Rubber Parts',
    description: 'Scrap rubber.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 50,
    weight: 0.1,
    recycleYield: [],
    requiredForWorkshop: true,
    requiredForExpedition: true,
  },
  {
    id: id('Ruined Accordion'),
    name: 'Ruined Accordion',
    description: 'Musical instrument.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 2.0,
    recycleYield: [
      { itemId: id('Rubber Parts'), amount: 18 },
      { itemId: id('Steel Spring'), amount: 3 },
    ],
  },
  {
    id: id('Ruined Augment'),
    name: 'Ruined Augment',
    description: 'Failed tech.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.2,
    recycleYield: [
      { itemId: id('Plastic Parts'), amount: 2 },
      { itemId: id('Rubber Parts'), amount: 2 },
    ],
  },
  {
    id: id('Ruined Baton'),
    name: 'Ruined Baton',
    description: 'Police weapon.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Metal Parts'), amount: 6 },
      { itemId: id('Rubber Parts'), amount: 3 },
    ],
  },
  {
    id: id('Ruined Handcuffs'),
    name: 'Ruined Handcuffs',
    description: 'Restraints.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.3,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 8 }],
  },
  {
    id: id('Ruined Parachute'),
    name: 'Ruined Parachute',
    description: 'Silk cloth.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 1.0,
    recycleYield: [{ itemId: id('Fabric'), amount: 10 }],
  },
  {
    id: id('Ruined Tactical Vest'),
    name: 'Ruined Tactical Vest',
    description: 'Body armor scraps.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 1.5,
    recycleYield: [
      { itemId: id('Fabric'), amount: 5 },
      { itemId: id('Magnet'), amount: 1 },
    ],
  },
  {
    id: id('Ruined Riot Shield'),
    name: 'Ruined Riot Shield',
    description: 'Polycarbonate shield.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 3.0,
    recycleYield: [
      { itemId: id('Plastic Parts'), amount: 10 },
      { itemId: id('Rubber Parts'), amount: 6 },
    ],
  },
  {
    id: id('Rusted Bolts'),
    name: 'Rusted Bolts',
    description: 'Fasteners.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.2,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 8 }],
  },
  {
    id: id('Rusted Gear'),
    name: 'Rusted Gear',
    description: 'Cog.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Metal Parts'), amount: 4 },
      { itemId: id('Mechanical Components'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Rusted Shut Medical Kit'),
    name: 'Rusted Shut Medical Kit',
    description: 'Old medkit.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Syringe'), amount: 2 },
      { itemId: id('Antiseptic'), amount: 1 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Rusted Tools'),
    name: 'Rusted Tools',
    description: 'Wrenches and stuff.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Metal Parts'), amount: 8 },
      { itemId: id('Steel Spring'), amount: 1 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Rusty ARC Steel'),
    name: 'Rusty ARC Steel',
    description: 'Old ARC metal.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 1.0,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 8 }],
  },
  {
    id: id('Sample Cleaner'),
    name: 'Sample Cleaner',
    description: 'Lab device.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Electrical Components'), amount: 2 },
      { itemId: id('Assorted Seeds'), amount: 14 },
    ],
  },
  {
    id: id('Sensors'),
    name: 'Sensors',
    description: 'Detects things.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 500,
    weight: 0.2,
    recycleYield: [
      { itemId: id('Wires'), amount: 2 },
      { itemId: id('Metal Parts'), amount: 2 },
    ],
    requiredForExpedition: true,
  },
  {
    id: id('Sentinel Firing Core'),
    name: 'Sentinel Firing Core',
    description: 'Weapon system from a Sentinel.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 2.0,
    recycleYield: [
      { itemId: id('ARC Alloy'), amount: 2 },
      { itemId: id('Mechanical Components'), amount: 3 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Shredder Gyro'),
    name: 'Shredder Gyro',
    description: 'Stabilizer.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Mechanical Components'), amount: 3 },
      { itemId: id('ARC Alloy'), amount: 3 },
    ],
  },
  {
    id: id('Signal Amplifier'),
    name: 'Signal Amplifier',
    description: 'Boosts signal strength.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Electrical Components'), amount: 2 },
      { itemId: id('Voltage Converter'), amount: 2 },
    ],
  },
  {
    id: id('Silver Teaspoon Set'),
    name: 'Silver Teaspoon Set',
    description: 'Fancy silverware.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 3000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Simple Gun Parts'),
    name: 'Simple Gun Parts',
    description: 'Basic weapon parts.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 330,
    weight: 0.5,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 2 }],
  },
  {
    id: id('Snitch Scanner'),
    name: 'Snitch Scanner',
    description: 'Eye of a Snitch.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('ARC Alloy'), amount: 4 },
      { itemId: id('Electrical Components'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Spaceport Container Storage Key'),
    name: 'Spaceport Container Storage Key',
    description: 'Key to container storage.',
    rarity: Rarity.RARE,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Spaceport Control Tower Key'),
    name: 'Spaceport Control Tower Key',
    description: 'Key to the control tower.',
    rarity: Rarity.RARE,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Spaceport Trench Tower Key'),
    name: 'Spaceport Trench Tower Key',
    description: 'Key to the trench tower.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Spaceport Warehouse Key'),
    name: 'Spaceport Warehouse Key',
    description: 'Key to the warehouse.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Speaker Component'),
    name: 'Speaker Component',
    description: 'Makes sound.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 500,
    weight: 0.3,
    recycleYield: [
      { itemId: id('Plastic Parts'), amount: 2 },
      { itemId: id('Rubber Parts'), amount: 2 },
    ],
  },
  {
    id: id('Spectrometer'),
    name: 'Spectrometer',
    description: 'Scientific instrument.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Advanced Electrical Components'), amount: 1 },
      { itemId: id('Sensors'), amount: 1 },
    ],
  },
  {
    id: id('Spectrum Analyzer'),
    name: 'Spectrum Analyzer',
    description: 'Analyzes spectrums.',
    rarity: Rarity.EPIC,
    type: ItemType.MATERIAL,
    sellPrice: 3500,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Sensors'), amount: 1 },
      { itemId: id('Exodus Modules'), amount: 1 },
    ],
  },
  {
    id: id('Spring Cushion'),
    name: 'Spring Cushion',
    description: 'Seat part.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Durable Cloth'), amount: 2 },
      { itemId: id('Steel Spring'), amount: 2 },
    ],
  },
  {
    id: id('Spotter Relay'),
    name: 'Spotter Relay',
    description: 'Targeting aid.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Electrical Components'), amount: 2 },
      { itemId: id('ARC Alloy'), amount: 1 },
    ],
  },
  {
    id: id('Statuette'),
    name: 'Statuette',
    description: 'Small figurine.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 3000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Steel Spring'),
    name: 'Steel Spring',
    description: 'Coiled metal.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 300,
    weight: 0.2,
    recycleYield: [{ itemId: id('Metal Parts'), amount: 3 }],
    requiredForExpedition: true,
  },
  {
    id: id('Stella Montis Archives Key'),
    name: 'Stella Montis Archives Key',
    description: 'Key to the archives.',
    rarity: Rarity.EPIC,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Stella Montis Assembly Admin Key'),
    name: 'Stella Montis Assembly Admin Key',
    description: 'Key to admin assembly.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Stella Montis Medical Storage Key'),
    name: 'Stella Montis Medical Storage Key',
    description: 'Key to medical storage.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Stella Montis Security Checkpoint Key'),
    name: 'Stella Montis Security Checkpoint Key',
    description: 'Key to security checkpoint.',
    rarity: Rarity.RARE,
    type: ItemType.KEY_ITEM,
    sellPrice: 100,
    weight: 0.1,
    recycleYield: [],
  },
  {
    id: id('Surveyor Vault'),
    name: 'Surveyor Vault',
    description: 'Data vault from a Surveyor.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Mechanical Components'), amount: 2 },
      { itemId: id('ARC Alloy'), amount: 2 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Synthesized Fuel'),
    name: 'Synthesized Fuel',
    description: 'High energy fuel.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 700,
    weight: 0.5,
    recycleYield: [{ itemId: id('Oil'), amount: 1 }, { itemId: id('Plastic Parts'), amount: 1 }],
    requiredForWorkshop: true,
  },
  {
    id: id('Syringe'),
    name: 'Syringe',
    description: 'Medical injector.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 500,
    weight: 0.1,
    recycleYield: [
      { itemId: id('Plastic Parts'), amount: 3 },
      { itemId: id('Chemicals'), amount: 2 },
    ],
  },
  {
    id: id('Tattered ARC Lining'),
    name: 'Tattered ARC Lining',
    description: 'Ripped insulation.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.5,
    recycleYield: [{ itemId: id('Fabric'), amount: 12 }],
  },
  {
    id: id('Tattered Clothes'),
    name: 'Tattered Clothes',
    description: 'Rags.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 0.5,
    recycleYield: [{ itemId: id('Fabric'), amount: 11 }],
  },
  {
    id: id('Telemetry Transceiver'),
    name: 'Telemetry Transceiver',
    description: 'Sends data.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 3000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Advanced Electrical Components'), amount: 1 },
      { itemId: id('Processor'), amount: 1 },
    ],
  },
  {
    id: id('Thermostat'),
    name: 'Thermostat',
    description: 'Temperature control.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Rubber Parts'), amount: 6 },
      { itemId: id('Sensors'), amount: 2 },
    ],
  },
  {
    id: id('Tick Pod'),
    name: 'Tick Pod',
    description: 'Egg of a Tick.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Chemicals'), amount: 1 },
      { itemId: id('Metal Parts'), amount: 1 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Toaster'),
    name: 'Toaster',
    description: 'Makes toast.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.5,
    recycleYield: [
      { itemId: id('Plastic Parts'), amount: 5 },
      { itemId: id('Wires'), amount: 3 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Torn Book'),
    name: 'Torn Book',
    description: 'Unreadable.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Torn Blanket'),
    name: 'Torn Blanket',
    description: 'Old bedding.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 640,
    weight: 1.0,
    recycleYield: [{ itemId: id('Fabric'), amount: 12 }],
  },
  {
    id: id('Turbo Pump'),
    name: 'Turbo Pump',
    description: 'High speed pump.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 2.0,
    recycleYield: [
      { itemId: id('Mechanical Components'), amount: 1 },
      { itemId: id('Oil'), amount: 3 },
    ],
  },
  {
    id: id('Unusable Weapon'),
    name: 'Unusable Weapon',
    description: 'Bent barrel.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 2000,
    weight: 3.0,
    recycleYield: [
      { itemId: id('Metal Parts'), amount: 4 },
      { itemId: id('Simple Gun Parts'), amount: 5 },
    ],
  },
  {
    id: id('Vase'),
    name: 'Vase',
    description: 'Decorative vessel.',
    rarity: Rarity.RARE,
    type: ItemType.VALUABLE,
    sellPrice: 3000,
    weight: 1.0,
    recycleYield: [],
  },
  {
    id: id('Very Comfortable Pillow'),
    name: 'Very Comfortable Pillow',
    description: 'Soft.',
    rarity: Rarity.COMMON,
    type: ItemType.VALUABLE,
    sellPrice: 2000,
    weight: 0.5,
    recycleYield: [],
  },
  {
    id: id('Volcanic Rock'),
    name: 'Volcanic Rock',
    description: 'Porous stone.',
    rarity: Rarity.COMMON,
    type: ItemType.MATERIAL,
    sellPrice: 270,
    weight: 1.0,
    recycleYield: [],
  },
  {
    id: id('Voltage Converter'),
    name: 'Voltage Converter',
    description: 'Steps power up or down.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 500,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Wires'), amount: 1 },
      { itemId: id('Rubber Parts'), amount: 1 },
    ],
  },
  {
    id: id('Wasp Driver'),
    name: 'Wasp Driver',
    description: 'Flight engine.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('ARC Alloy'), amount: 1 },
      { itemId: id('Electrical Components'), amount: 1 },
    ],
    requiredForWorkshop: true,
  },
  {
    id: id('Water Filter'),
    name: 'Water Filter',
    description: 'Purifies water.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 0.5,
    recycleYield: [
      { itemId: id('Rubber Parts'), amount: 2 },
      { itemId: id('Canister'), amount: 3 },
    ],
  },
  {
    id: id('Water Pump'),
    name: 'Water Pump',
    description: 'Moves water.',
    rarity: Rarity.RARE,
    type: ItemType.MATERIAL,
    sellPrice: 1000,
    weight: 1.0,
    recycleYield: [
      { itemId: id('Metal Parts'), amount: 4 },
      { itemId: id('Oil'), amount: 2 },
    ],
  },
  {
    id: id('Wires'),
    name: 'Wires',
    description: 'Conductive cabling.',
    rarity: Rarity.UNCOMMON,
    type: ItemType.MATERIAL,
    sellPrice: 200,
    weight: 0.1,
    recycleYield: [{ itemId: id('Rubber Parts'), amount: 2 }],
    requiredForExpedition: true,
  },
];

export const QUESTS: Quest[] = [
  {
    id: id('Picking Up The Pieces'),
    name: 'Picking Up The Pieces',
    giver: 'Shani',
    description: 'Visit any area with a loot category icon and loot 3 containers.',
    objectives: [
      { description: 'Visit any area on your map with a loot category icon' },
      { description: 'Loot 3 containers' },
    ],
    rewards: { text: ['1x Rattler III', '80x Medium Ammo'] },
  },
  {
    id: id('Trash Into Treasure'),
    name: 'Trash Into Treasure',
    giver: 'Shani',
    description: 'Gather basic components for Shani.',
    objectives: [
      { description: 'Obtain 6 Wires', targetItemId: id('Wires'), count: 6 },
      { description: 'Obtain 1 Battery', targetItemId: id('Battery'), count: 1 },
    ],
    rewards: { text: ['1x Tactical Mk. 1', '3x Adrenaline Shot'] },
  },
  {
    id: id('Clearer Skies'),
    name: 'Clearer Skies',
    giver: 'Shani',
    description: 'Clear out the ARC threat.',
    objectives: [
      { description: 'Destroy 3 ARC enemies' },
      { description: 'Get 3 ARC Alloy for Shani', targetItemId: id('ARC Alloy'), count: 3 },
    ],
    rewards: { text: ['1x Backpack Cosmetic (Black - Hiker Color)', '3x Sterilized Bandage', '1x Light Shield'] },
  },
  {
    id: id('Off The Radar'),
    name: 'Off The Radar',
    giver: 'Shani',
    description: 'Repair the comms.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Visit a Field Depot' },
      { description: 'Repair the antenna on the roof of the Field Depot' },
    ],
    rewards: { text: ['2x Defibrillator'] },
  },
  {
    id: id('A Bad Feeling'),
    name: 'A Bad Feeling',
    giver: 'Celeste',
    description: 'Investigate ARC activity.',
    objectives: [
      { description: 'Find and search any ARC Probe or ARC Courier' },
    ],
    rewards: { itemIds: [id('Metal Parts'), id('Steel Spring'), id('Duct Tape')], text: ['10x Metal Parts', '5x Steel Spring', '5x Duct Tape'] },
  },
  {
    id: id('A Balanced Harvest'),
    name: 'A Balanced Harvest',
    giver: 'Celeste',
    description: 'Search for agricultural data at Dam Battlegrounds.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Go to the Research & Administration building' },
      { description: 'Locate Lab 1 on the upper floor above the reception' },
      { description: 'Search for any traces of the agricultural research project' },
    ],
    rewards: { itemIds: [id('Advanced Mechanical Components'), id('Medium Gun Parts'), id('Steel Spring')], text: ['3x Adv. Mech Components', '3x Medium Gun Parts', '10x Steel Spring'] },
  },
  {
    id: id('A Better Use'),
    name: 'A Better Use',
    giver: 'Tian Wen',
    description: 'Secure supply drops.',
    objectives: [
      { description: 'Request in a Supply Drop from a Call Station' },
      { description: 'Loot a Supply Drop' },
    ],
    rewards: { text: ['Extended Light Magazine I', 'Compensator I', 'Stable Stock I'] },
  },
  {
    id: id('A Lay Of The Land'),
    name: 'A Lay Of The Land',
    giver: 'Shani',
    description: 'Scout the Spaceport.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Reach the Jiangsu Warehouse' },
      { description: 'Find the shipping notes in the foremans office' },
      { description: 'Locate the scanners on the upper floor of Control Tower A6' },
      { description: 'Deliver 1 LiDAR Scanners to Shani' },
    ],
    rewards: { itemIds: [id('Dam Testing Annex Key')], text: ['Dam Testing Annex Key', '3x Zipline', '2x Smoke Grenade'] },
  },
  {
    id: id('A New Type Of Plant'),
    name: 'A New Type Of Plant',
    giver: 'Lance',
    description: 'Find a rare plant sample.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Search for the new plant near the Baron Husk in the Old Battleground' },
      { description: 'Deliver the Possibly Toxic Plant to Lance' },
    ],
    rewards: { itemIds: [id('Antiseptic')], text: ['1x Vita Shot', '5x Antiseptic'] },
  },
  {
    id: id('A Reveal in Ruins'),
    name: 'A Reveal in Ruins',
    giver: 'Lance',
    description: 'Find medical equipment in Buried City.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Search for an ESR Analyzer inside any pharmacy in Buried City' },
      { description: 'Deliver the ESR Analyzer to Lance' },
    ],
    rewards: { text: ['Tactical Mk. 3 (Healing)', '1x Surge Shield Recharger'] },
  },
  {
    id: id('A Symbol Of Unification'),
    name: 'A Symbol Of Unification',
    giver: 'Celeste',
    description: 'Raise the flag at Formicai Outpost.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Reach the Formicai Outpost in Dam Battlegrounds' },
      { description: 'Locate the flag at Formicai Outpost' },
      { description: 'Hoist the flag on the small platform overlooking the Red Lake' },
    ],
    rewards: { itemIds: [id('Mod Components'), id('Duct Tape')], text: ['Aviator (Outfit)', '3x Mod Components', '5x Duct Tape'] },
  },
  {
    id: id('A Warm Place To Rest'),
    name: 'A Warm Place To Rest',
    giver: 'Apollo',
    description: 'Investigate the highway camp.',
    objectives: [
      { description: 'Locate the Abandoned Highway Camp' },
      { description: 'Search for any signs of survivors' },
      { description: 'Follow the red markers' },
      { description: 'Inspect the grave' },
    ],
    rewards: { itemIds: [id('Rosary')], text: ['Radio Renegade (Outfit - Goggles)', '3x Noisemaker', '5x Blue Light Stick', '1x Rosary'] },
  },
  {
    id: id('After Rain Comes'),
    name: 'After Rain Comes',
    giver: 'Celeste',
    description: 'Repair solar panels.',
    objectives: [
      { description: 'Find the flooded solar panels nearby the Grandioso Apartments' },
      { description: 'Repair the solar panels using 5 Wires and 2 Batteries', targetItemId: id('Wires'), count: 5 },
    ],
    rewards: { itemIds: [id('Antiseptic'), id('Durable Cloth')], text: ['5x Blue Light Stick', '3x Antiseptic', '5x Durable Cloth'] },
  },
  {
    id: id('Armored Transports'),
    name: 'Armored Transports',
    giver: 'Tian Wen',
    description: 'Loot armored cars at Blue Gate.',
    objectives: [
      { description: 'Reach the Checkpoint' },
      { description: 'Search the Guard huts for a Armored Patrol Key Card' },
      { description: 'Reach the Traffic Tunnel near the Blue Gate Checkpoint' },
      { description: 'Find and unlock the rear door of an armored patrol car' },
    ],
    rewards: { text: ['Blue Yellow (Aviator Color)', '3x Smoke Grenade', '3x Defibrillator'] },
  },
  {
    id: id('Back On Top'),
    name: 'Back On Top',
    giver: 'Tian Wen',
    description: 'Mark strategic locations.',
    objectives: [
      { description: 'On The Blue Gate, mark the white lookout tower south of the Warehouse Complex' },
      { description: 'On Dam Battlegrounds, mark the Pattern House' },
      { description: 'On Spaceport, mark the South Trench Tower' },
      { description: 'On Buried City, mark the building with the mural in the Buried Properties' },
    ],
    rewards: { text: ['Renegade I', 'Stable Stock III', '80x Medium Ammo'] },
  },
  {
    id: id('Bees!'),
    name: 'Bees!',
    giver: 'Celeste',
    description: 'Check the hives.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Reach the Olive Grove in Blue Gate' },
      { description: 'Search the bee hives around the Olive Grove' },
    ],
    rewards: { itemIds: [id('Advanced Electrical Components'), id('Sensors')], text: ['1x Advanced Electrical Components', '3x Sensors'] },
  },
  {
    id: id('Broken Monument'),
    name: 'Broken Monument',
    giver: 'Tian Wen',
    description: 'Recover First Wave artifacts.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Reach the hallowed grounds by the Scrap Yard' },
      { description: 'Search for a compass near the broken-down vehicles' },
      { description: 'Search for the video tape near the cylindrical containers' },
      { description: 'Search for the old field rations in the Raider camp' },
      { description: 'Deliver the First Wave Tape to Tian Wen' },
      { description: 'Deliver First Wave Compass to Tian Wen' },
      { description: 'Deliver First Wave Rations to Tian Wen' },
    ],
    rewards: { text: ['Arpeggio I', 'Compensator II', '80x Medium Ammo'] },
  },
  {
    id: id('Building A Library'),
    name: 'Building A Library',
    giver: 'Apollo',
    description: 'Find books for the community.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Locate the Library in the City Center' },
      { description: 'Find 1 romance book' },
      { description: 'Find 1 detective book' },
      { description: 'Find 1 adventure book' },
    ],
    rewards: { itemIds: [id('Buried City Town Hall Key')], text: ['Buried City Town Hall Key'] },
  },
  {
    id: id('Celestes Journals'),
    name: "Celeste's Journals",
    giver: 'Celeste',
    description: 'Recover lost journals.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Retrieve Celestes Journals from the South Swamp Outpost' },
      { description: 'Retrieve Celestes Journals from the northern outpost overlooking the Red Lakes' },
      { description: 'Deliver 2 Journals to Celeste' },
    ],
    rewards: { itemIds: [id('Magnetic Accelerator'), id('Heavy Gun Parts'), id('Exodus Modules')], text: ['1x Magnetic Accelerator', '3x Heavy Gun Parts', '1x Exodus Modules'] },
  },
  {
    id: id('Communication Hideout'),
    name: 'Communication Hideout',
    giver: 'Shani',
    description: 'Restore the Red Tower.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Reach the Red Tower in Old Town' },
      { description: 'Find missing battery cell' },
      { description: 'Install the battery cell in the Generator' },
      { description: 'Enable the power on the Generator' },
      { description: 'Boot the antenna terminal near the Red Tower' },
    ],
    rewards: { text: ['Aviator (Outfit - Crimson Racer)', 'Anvil III', '40x Heavy Ammo'] },
  },
  {
    id: id('Digging Up Dirt'),
    name: 'Digging Up Dirt',
    giver: 'Celeste',
    description: 'Locate the dead drop.',
    objectives: [
      { description: 'Locate the Santa Maria Houses in Old Town' },
      { description: 'Locate the Dead Drop inside the courtyard' },
    ],
    rewards: { itemIds: [id('Advanced Electrical Components'), id('Speaker Component')], text: ['x2 Advanced Electrical Components', 'x4 Speaker Component'] },
  },
  {
    id: id('Doctors Orders'),
    name: "Doctor's Orders",
    giver: 'Lance',
    description: 'Gather medical supplies.',
    objectives: [
      { description: 'Obtain 1 Syringe', targetItemId: id('Syringe'), count: 1 },
      { description: 'Obtain 2 Antiseptic', targetItemId: id('Antiseptic'), count: 2 },
      { description: 'Obtain 1 Durable Cloth', targetItemId: id('Durable Cloth'), count: 1 },
      { description: 'Obtain 1 Great Mullein', targetItemId: id('Great Mullein'), count: 1 },
    ],
    rewards: { text: ['3x Adrenaline Shot', '3x Sterilized Bandage', '1x Surge Shield Recharger'] },
  },
  {
    id: id('Dormant Barons'),
    name: 'Dormant Barons',
    giver: 'Shani',
    description: 'Loot a Baron.',
    objectives: [
      { description: 'Loot a Baron Husk' },
    ],
    rewards: { text: ['3x Door Blocker', '3x Lil Smoke Grenade'] },
  },
  {
    id: id('Down To Earth'),
    name: 'Down To Earth',
    giver: 'Shani',
    description: 'Secure a field crate.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Visit a Field Depot' },
      { description: 'Deliver a Field Crate to a Supply Station' },
      { description: 'Collect the reward' },
    ],
    rewards: { text: ['Combat Mk. 1', 'Medium Shield'] },
  },
  {
    id: id('Echoes Of Victory Ridge'),
    name: 'Echoes Of Victory Ridge',
    giver: 'Celeste',
    description: 'Recover battle plans.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Reach Victory Ridge' },
      { description: 'Retrieve the battle plans from the hideout under the broken highway' },
      { description: 'Deliver Major Aivas Patch to Celeste' },
    ],
    rewards: { itemIds: [id('Crude Explosives'), id('Processor'), id('Music Box')], text: ['6x Crude Explosives', '2x Processor', '1x Music Box'] },
  },
  {
    id: id('Espresso'),
    name: 'Espresso',
    giver: 'Apollo',
    description: 'Salvage a coffee machine.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Find an espresso machine to salvage for spare parts' },
      { description: 'Get the Espresso Machine Parts for Apollo' },
    ],
    rewards: { itemIds: [id('Coffee Pot')], text: ['1x Coffee Pot', '3x Adrenaline Shot'] },
  },
  {
    id: id('Eyes In The Sky'),
    name: 'Eyes In The Sky',
    giver: 'Shani',
    description: 'Deploy LiDAR scanners.',
    objectives: [
      { description: 'On Dam Battlegrounds, install a LiDAR Scanner at the top of the Control Tower' },
      { description: 'On Spaceport, install a LiDAR Scanner at the Communications Tower' },
      { description: 'On Buried City, install a LiDAR Scanner on top of the Galleria sign' },
    ],
    rewards: { text: ['3x Tagging Grenade', '1x Vita Spray', '5x Yellow Light Stick'] },
  },
  {
    id: id('Eyes On The Prize'),
    name: 'Eyes On The Prize',
    giver: 'Tian Wen',
    description: 'Rewire solar panels.',
    objectives: [
      { description: 'Find the secluded roof terrace south-west of the Southern Station, look for blue tarps.' },
      { description: 'Rewire the solar panel using 3 Wires', targetItemId: id('Wires'), count: 3 },
    ],
    rewards: { text: ['1x Extended Shotgun Mag II', '1x Extended Medium Mag II'] },
  },
  {
    id: id('Flickering Threat'),
    name: 'Flickering Threat',
    giver: 'Celeste',
    description: 'Restore power at the dam.',
    objectives: [
      { description: 'Enter the Power Generation Complex by The Dam' },
      { description: 'Find the Generator Room' },
      { description: 'Repair the Generator' },
      { description: 'Find the Ventilation Shaft' },
      { description: 'Enable the power via the power switch underneath the stairs' },
    ],
    rewards: { itemIds: [id('Medium Gun Parts'), id('Advanced Mechanical Components')], text: ['Radio Renegade (Outfit - Helmet)', '5x Medium Gun Parts', '3x Adv. Mech Components'] },
  },
  {
    id: id('Greasing Her Palms'),
    name: 'Greasing Her Palms',
    giver: 'Celeste',
    description: 'Scout locations for Celeste.',
    objectives: [
      { description: 'On Spaceport, scope out the rocket thrusters outside the Rocket Assembly' },
      { description: 'On Dam Battlegrounds, visit the Locked Room in the Water Treatment Control building' },
      { description: 'On Buried City, visit the barricaded area on floor 6 of the Space Travel Building' },
    ],
    rewards: { itemIds: [id('Speaker Component'), id('Electrical Components')], text: ['Lure Grenade Blueprint', 'Speaker Component', 'Electrical Components'] },
  },
  {
    id: id('Hatch Repairs'),
    name: 'Hatch Repairs',
    giver: 'Shani',
    description: 'Fix the hatch.',
    objectives: [
      { description: 'Repair the leaking hydraulic pipes near a Raider Hatch' },
      { description: 'Search for a Hatch Key near the Raider Hatch' },
    ],
    rewards: { itemIds: [id('Raider Hatch Key')], text: ['1x Raider Hatch Key', '1x Binoculars'] },
  },
  {
    id: id('Industrial Espionage'),
    name: 'Industrial Espionage',
    giver: 'Tian Wen',
    description: 'Bug the cache.',
    objectives: [
      { description: 'Find Tian Wens weapon cache near the Gas Station in the Outskirts' },
      { description: 'Deliver the Burletta to the rival weapon cache' },
      { description: 'Plant a bug on the weapon cache' },
    ],
    rewards: { itemIds: [id('Mechanical Components'), id('Simple Gun Parts')], text: ['Burletta Blueprint', '3x Mech Components', '3x Simple Gun Parts'] },
  },
  {
    id: id('Into The Fray'),
    name: 'Into The Fray',
    giver: 'Shani',
    description: 'Hunt a Leaper.',
    objectives: [
      { description: 'Destroy a Leaper' },
      { description: 'Obtain a Leaper Pulse Unit', targetItemId: id('Leaper Pulse Unit'), count: 1 },
    ],
    rewards: { text: ['Outfit (Radio Renegade)', 'Backpack Charm (Burger Boy)', '1x Vulcano III', '40x Shotgun Ammo'] },
  },
  {
    id: id('Keeping The Memory'),
    name: 'Keeping The Memory',
    giver: 'Celeste',
    description: 'Recover the helmet.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Reach the wreckage in the Formicai Hills' },
      { description: 'Search for the missing helmet' },
      { description: 'Return the helmet to the memorial' },
    ],
    rewards: { itemIds: [id('Simple Gun Parts'), id('Duct Tape'), id('Magnet')], text: ['5x Simple Gun Parts', '5x Duct Tape', '5x Magnet'] },
  },
  {
    id: id('Life Of A Pharmacist'),
    name: 'Life Of A Pharmacist',
    giver: 'Lance',
    description: 'Document the pharmacist.',
    objectives: [
      { description: 'Find the Arbusto Farmacia by the collapsed highway' },
      { description: 'Document the pharmacists hobbies' },
      { description: 'Document the pharmacists family' },
      { description: 'Document the pharmacists taste' },
      { description: 'Document the pharmacists skills' },
    ],
    rewards: { text: ['1x Defibrillator', '1x Surge Shield Recharger', '3x Sterilized Bandage'] },
  },
  {
    id: id('Lost In Transmission'),
    name: 'Lost In Transmission',
    giver: 'Shani',
    description: 'Connect from the tower.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Visit Control Tower A6' },
      { description: 'Reach the top of Control Tower A6' },
      { description: 'Establish a connection from the terminal' },
    ],
    rewards: { text: ['Snap Hook'] },
  },
  {
    id: id('Marked For Death'),
    name: 'Marked For Death',
    giver: 'Tian Wen',
    description: 'Find the cache.',
    objectives: [
      { description: 'Reach the Su Durante Warehouses in the Outskirts in Buried City' },
      { description: 'Search for Tian Wens cache near the Warehouses' },
      { description: 'Follow the clues' },
    ],
    rewards: { text: ['Shotgun Choke II', 'Angled Grip II'] },
  },
  {
    id: id('Market Correction'),
    name: 'Market Correction',
    giver: 'Tian Wen',
    description: 'Sabotage.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Locate the cache near Marano Station' },
      { description: 'Sabotage the cache' },
    ],
    rewards: { text: ['1x Silencer II', '1x Extended Light Mag I', '1x Compensator I'] },
  },
  {
    id: id('Medical Merchandise'),
    name: 'Medical Merchandise',
    giver: 'Lance',
    description: 'Loot medical supplies.',
    objectives: [
      { description: 'On Spaceport, search 2 containers in the Departure Buildings exam rooms' },
      { description: 'Search 3 containers in the Hospital in Buried City' },
      { description: 'On Dam Battlegrounds, search 2 containers in the Research & Administration buildings medical room' },
    ],
    rewards: { text: ['Banana (Charm)', '3x Defibrillator', '2x Vita Shot'] },
  },
  {
    id: id('Mixed Signals'),
    name: 'Mixed Signals',
    giver: 'Shani',
    description: 'Destroy a Surveyor.',
    objectives: [
      { description: 'Destroy an ARC Surveyor' },
      { description: 'Obtain 1 Surveyor Vault', targetItemId: id('Surveyor Vault'), count: 1 },
    ],
    rewards: { itemIds: [id('Raider Hatch Key')], text: ['Photoelectric Cloak', 'Raider Hatch Key'] },
  },
  {
    id: id('Our Presence Up There'),
    name: 'Our Presence Up There',
    giver: 'Shani',
    description: 'Install antenna.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Visit the Pattern House in The Dam' },
      { description: 'Find and flip the power switch' },
      { description: 'Complete the antenna installation on the roof' },
    ],
    rewards: { itemIds: [id('Buried City Town Hall Key'), id('Raider Hatch Key')], text: ['Buried City Town Hall Key', 'Raider Hatch Key', '3x Jolt Mine'] },
  },
  {
    id: id('Out Of The Shadows'),
    name: 'Out Of The Shadows',
    giver: 'Shani',
    description: 'Destroy a Rocketeer.',
    objectives: [
      { description: 'Destroy a Rocketeer' },
      { description: 'Obtain a Rocketeer Driver', targetItemId: id('Rocketeer Driver'), count: 1 },
    ],
    rewards: { text: ['3x Surge Shield Recharger', '2x Wolfpack'] },
  },
  {
    id: id('Power Out'),
    name: 'Power Out',
    giver: 'Celeste',
    description: 'Restore power.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Find the Electrical Substation south of the Spaceport' },
      { description: 'Find any sign of the missing engineer' },
      { description: 'Install the fuse' },
      { description: 'Restore the power' },
    ],
    rewards: { itemIds: [id('Wires'), id('Explosive Compound'), id('Oil')], text: ['Bag (Radio Renegade Variant)', '5x Wires', '5x Explosive Compound', '5x Oil'] },
  },
  {
    id: id('Prescriptions Of The Past'),
    name: 'Prescriptions Of The Past',
    giver: 'Lance',
    description: 'Find records.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Visit the Departure Building in Spaceport' },
      { description: 'Find the Medical Exam Room inside the Departure Building' },
      { description: 'Search for the records' },
    ],
    rewards: { text: ['Heavy Shield', 'Tactical Mk. 3 (Healing)', '3x Adrenaline Shot'] },
  },
  {
    id: id('Safe Passage'),
    name: 'Safe Passage',
    giver: 'Apollo',
    description: 'Clear the way.',
    objectives: [
      { description: 'Destroy 2 ARC enemies using any explosive grenade' },
    ],
    rewards: { text: ['5x Lil Smoke Grenade', '3x Shrapnel Grenade', '3x Barricade Kit'] },
  },
  {
    id: id('Source Of The Contamination'),
    name: 'Source Of The Contamination',
    giver: 'Celeste',
    description: 'Investigate the water supply.',
    objectives: [
      { description: 'Reach the Water Treatment Building in The Dam' },
      { description: 'Search for the Flood Spill Intake near the Swamp' },
      { description: 'Investigate any suspicious objects' },
    ],
    rewards: { itemIds: [id('Steel Spring'), id('Duct Tape'), id('Mod Components')], text: ['5x Steel Spring', '5x Duct Tape', '1x Mod Components'] },
  },
  {
    id: id('Sparks Fly'),
    name: 'Sparks Fly',
    giver: 'Apollo',
    description: 'Destroy a Hornet.',
    objectives: [
      { description: 'Destroy a Hornet with a Trigger Nade or Snap Blast Grenade' },
    ],
    rewards: { itemIds: [id('Crude Explosives'), id('Processor')], text: ['4x Crude Explosives', '2x Processor', 'Trigger Nade Blueprint'] },
  },
  {
    id: id('Straight Record'),
    name: 'Straight Record',
    giver: 'Celeste',
    description: 'Disable the EMP.',
    objectives: [
      { description: 'Reach Victory Ridge' },
      { description: 'Find the old EMP trap' },
      { description: 'Disable the first power switch' },
      { description: 'Disable the second power switch' },
      { description: 'Disable the third power switch' },
      { description: 'Shut down the EMP trap' },
    ],
    rewards: { itemIds: [id('Medium Gun Parts'), id('Advanced Mechanical Components')], text: ['5x Medium Gun Parts', '3x Adv. Mech Components'] },
  },
  {
    id: id('Switching The Supply'),
    name: 'Switching The Supply',
    giver: 'Celeste',
    description: 'Turn the valve.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Find the tunnels under the Spaceport' },
      { description: 'Find and turn the valve in the tunnels under Spaceport' },
    ],
    rewards: { itemIds: [id('Spaceport Trench Tower Key'), id('Synthesized Fuel')], text: ['Radio Renegade (Outfit - Blue)', 'Spaceport Trench Tower Key', '3x Synthesized Fuel'] },
  },
  {
    id: id('The Right Tool'),
    name: 'The Right Tool',
    giver: 'Tian Wen',
    description: 'Combat challenge.',
    objectives: [
      { description: 'Destroy a Fireball' },
      { description: 'Destroy a Hornet' },
      { description: 'Destroy a Turret' },
    ],
    rewards: { text: ['Cheer Emote', '1x Stitcher II', '1x Extended Light Mag I'] },
  },
  {
    id: id('The Root Of The Matter'),
    name: 'The Root Of The Matter',
    giver: 'Celeste',
    description: 'Find the seed vault.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Go to the Research Building' },
      { description: 'Search for the seed vault in the room with a great view' },
      { description: 'Deliver the Experimental Seed Sample to Celeste' },
    ],
    rewards: { currency: 1000, text: ['Succulent (Charm)'] },
  },
  {
    id: id('The Majors Footlocker'),
    name: "The Major's Footlocker",
    giver: 'Tian Wen',
    description: 'Find mementos.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Search for Major Aivas mementos in the apartments northwest of The Dam' },
      { description: 'Deliver Major Aivas Mementos to Tian Wen' },
    ],
    rewards: { text: ['Hullcracker Blueprint'] },
  },
  {
    id: id('The Trifecta'),
    name: 'The Trifecta',
    giver: 'Shani',
    description: 'Collect drivers.',
    objectives: [
      { description: 'Destroy a Wasp' },
      { description: 'Get a Wasp Driver for Shani', targetItemId: id('Wasp Driver'), count: 1 },
      { description: 'Destroy a Hornet' },
      { description: 'Get a Hornet Driver for Shani', targetItemId: id('Hornet Driver'), count: 1 },
      { description: 'Destroy a Snitch' },
      { description: 'Get a Snitch Scanner for Shani', targetItemId: id('Snitch Scanner'), count: 1 },
    ],
    rewards: { itemIds: [id('Raider Hatch Key'), id('Dam Control Tower Key')], text: ['Skin Orange Camo', '1x Raider Hatch Key', '2x Defibrillator', '1x Dam Control Tower Key'] },
  },
  {
    id: id('Tribute to Toledo'),
    name: 'Tribute to Toledo',
    giver: 'Celeste',
    description: 'Get power.',
    objectives: [
      { description: 'Get a Power Rod for Celeste', targetItemId: id('Power Rod'), count: 1 },
    ],
    rewards: { itemIds: [id('Dam Staff Room Key')], text: ['Dam Staff Room Key'] },
  },
  {
    id: id('Turnabout'),
    name: 'Turnabout',
    giver: 'Celeste',
    description: 'Upload files.',
    objectives: [
      { description: 'Go to the North Trench Tower' },
      { description: 'Locate and upload the blackmail files to Celeste' },
    ],
    rewards: { itemIds: [id('Heavy Gun Parts'), id('Medium Gun Parts')], text: ['2x Heavy Gun Parts', '2x Medium Gun Parts'] },
  },
  {
    id: id('Unexpected Initiative'),
    name: 'Unexpected Initiative',
    giver: 'Tian Wen',
    description: 'Deliver supplies.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Reach the Grandioso Apartments in Buried City' },
      { description: 'Search for Fertilizer on the rooftop of the Grandioso Apartments' },
      { description: 'Reach Piazza Roma in Buried City' },
      { description: 'Search for a Water Pump in the broken rooftop gardens at Piazza Roma' },
      { description: 'Deliver a Water Pump to Tian Wen', targetItemId: id('Water Pump'), count: 1 },
      { description: 'Deliver Fertilizer to Tian Wen', targetItemId: id('Fertilizer'), count: 1 },
    ],
    rewards: { text: ['Il Toro I', '40x Shotgun Ammo', 'Shotgun Choke II'] },
  },
  {
    id: id('Untended Garden'),
    name: 'Untended Garden',
    giver: 'Celeste',
    description: 'Access archives.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Go to the Hydroponic Dome Complex' },
      { description: 'Access the data archive in one of the domes' },
      { description: 'Upload the data to the computer terminal in any Field Depot' },
    ],
    rewards: { itemIds: [id('Advanced Mechanical Components'), id('Heavy Gun Parts'), id('Canister')], text: ['3x Adv. Mech Components', '3x Heavy Gun Parts', '5x Canister'] },
  },
  {
    id: id('Water Troubles'),
    name: 'Water Troubles',
    giver: 'Celeste',
    description: 'Fix water supply.',
    objectives: [
      { description: 'In One Round' },
      { description: 'Locate the Flood Access Tunnel under the Red Lake Balcony' },
      { description: 'Find the intake to the Districts Water Supply' },
    ],
    rewards: { itemIds: [id('Mechanical Components'), id('Simple Gun Parts'), id('Steel Spring')], text: ['3x Mechanical Components', '3x Simple Gun Parts', '3x Steel Spring'] },
  },
  {
    id: id('What Goes Around'),
    name: 'What Goes Around',
    giver: 'Apollo',
    description: 'Use a burner.',
    objectives: [
      { description: 'Destroy any ARC using a Fireball Burner' },
    ],
    rewards: { text: ['Cobalt (Junior Color)', '3x Blaze Grenade', '2x Noisemaker', '5x Blue Light Stick'] },
  },
  {
    id: id('What We Left Behind'),
    name: 'What We Left Behind',
    giver: 'Tian Wen',
    description: 'Search containers.',
    objectives: [
      { description: 'On Buried City, search 2 containers in the Raider Camp beneath the Parking Garage' },
      { description: 'On Dam Battlegrounds, search for anything significant in the South Swamp Outpost' },
      { description: 'On Spaceport, search for anything significant in Bilguuns Hideout, next to the Container Storage' },
    ],
    rewards: { text: ['Muzzle Brake II', 'Vertical Grip II', 'Stable Stock II'] },
  },
];